### PR TITLE
add basic functions to use XPlot.Plotly with IFsharp.

### PR DESCRIPTION
**Pull request by npmurphy**

### CODE REVIEW

**Comment by tpetricek** [comment]
Having an integration for XPlot in IFSharp would be awesome!

I'm quite curious why you need to do changes in XPlot in order to integrate it with IFSharp? Ideally, the core API exposed by XPlot would be good enough so that integration with any other environment can be done on the other side (so that we do not have to change XPlot to support all other environments).

What would be the minimal thing to add to XPlot so that all the IFSharp-specific things can be handled in on the IFSharp side?

**Comment by npmurphy** [comment]
XPlot did not provide an easy way to access the the HTML of the chart as opposed to a complete HTML document containing the chart. 
For a notebook like environment the minimal thing is a function that returns the HTML of the chart div as a string. 
I have added that function in a non IFSharp specific way. 

I have modified the branch now so that the same code is used when we generate a figure for a notebook or for a HTML document. 
If you use Plotly.Show then you see a document in a new tab in the browser. 
If you use Plotly.IShow then you get a HTML string of the chart which can be rendered by any HTML viewer.

**Comment by TahaHachana** [comment]
Hello, 

Thanks for the pull request. I was in the process of migrating from calling Plotly's API to using the recently open-sourced JS library and as you noted a method that returns only the chart's HTML bits and not an entire document is indeed necessary first for the existing FsLab integration and also for other scenarios like Jupyter in this case or [ASP.NET](http://blog.leifbattermann.de/2015/11/07/xplot-hello-world/).

What do you think about making things more generic here with a simple "GetInlineHtml" member that returns the container div and the chart's script and moving the IFSharp specific integration to a separate component?

**Comment by npmurphy** [comment]
Hi @TahaHachana 

I think the `GetInlineHtml` function is pretty close to what is named `IShow` in this PR. 
I dont mind what it is named so long as the div id is a unique number each time the function is called.
The counter that is used in master is reinitialised each time we plot in the notebook environment.

I think by "IFSharp specific" you mean the `Plotly.InitialiseNotebook ()`? 
I agree that it could be pulled out into a `notebook_initialise_plotly.fsx` script that 
also defines something like 
```fsharp 
let plot g  = g |> Plotly.Plot |> Plotly.IShow |> Util.Html
```

**Comment by npmurphy** [comment]
XPlot now has the functions needed to support IfSharp, PR no longer needed. 
https://github.com/fsprojects/IfSharp/pull/61

**Pull request closed without merging**
